language: objective-c
osx_image: xcode8.2
script:
 - mkdir Build
 - cd Build
 - cmake -G Xcode ../
 - xcodebuild -project Quip.xcodeproj -list
 - xcodebuild -project Quip.xcodeproj -configuration Release build
