#!/bin/sh

# This script facilitates launching Quip from the command-line. It will first
# check for the existence of $QUIP_LOCATION (which should point to the desired
# Quip.app bundle) and launch it. If $QUIP_LOCATION does not exist or if it
# refers to a bundle that doesn't exist, the script falls back to looking for
# Quip in the Applications directory.
#
# $QUIP_LOCATION must be an absolute path.

if [ ! -d "$QUIP_LOCATION" ]; then
  QUIP_LOCATION="/Applications/Quip.app"
fi

if [ ! -d "$QUIP_LOCATION" ]; then
  exit 1
fi

open -a "$QUIP_LOCATION" $1
